# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "rapido-css"
  s.version = ""

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Raffaele Rasini"]
  s.date = "2013-06-01"
  s.description = "TODO: longer description of your gem"
  s.email = "raffaele.rasini@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    "Gemfile",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "lib/rapido-css.rb",
    "lib/rapido-css/rails.rb",
    "lib/rapido-css/rails/engine.rb",
    "rapido-css.gemspec",
    "stylesheets/rapido-css/_components.scss",
    "stylesheets/rapido-css/_default-styles.scss",
    "stylesheets/rapido-css/_functions.scss",
    "stylesheets/rapido-css/_normalize.scss",
    "stylesheets/rapido-css/_rapido.scss",
    "stylesheets/rapido-css/_settings.scss",
    "stylesheets/rapido-css/_susy.scss",
    "stylesheets/rapido-css/_utilities.scss",
    "stylesheets/rapido-css/components/_alerts.scss",
    "stylesheets/rapido-css/components/_breadcrumbs.scss",
    "stylesheets/rapido-css/components/_button-groups.scss",
    "stylesheets/rapido-css/components/_buttons.scss",
    "stylesheets/rapido-css/components/_captions.scss",
    "stylesheets/rapido-css/components/_close.scss",
    "stylesheets/rapido-css/components/_dropdowns.scss",
    "stylesheets/rapido-css/components/_forms.scss",
    "stylesheets/rapido-css/components/_images.scss",
    "stylesheets/rapido-css/components/_modals.scss",
    "stylesheets/rapido-css/components/_navs.scss",
    "stylesheets/rapido-css/components/_pager.scss",
    "stylesheets/rapido-css/components/_pagination.scss",
    "stylesheets/rapido-css/components/_pills.scss",
    "stylesheets/rapido-css/components/_responsive-navs.scss",
    "stylesheets/rapido-css/components/_sliders.scss",
    "stylesheets/rapido-css/components/_tables.scss",
    "stylesheets/rapido-css/components/_tabs.scss",
    "stylesheets/rapido-css/components/_type.scss",
    "stylesheets/rapido-css/settings/_base.scss",
    "stylesheets/rapido-css/settings/_colors.scss",
    "stylesheets/rapido-css/settings/_components.scss",
    "stylesheets/rapido-css/settings/_dimensions.scss",
    "stylesheets/rapido-css/settings/_effects.scss",
    "stylesheets/rapido-css/susy/_susy_background.scss",
    "stylesheets/rapido-css/susy/_susy_functions.scss",
    "stylesheets/rapido-css/susy/_susy_grid.scss",
    "stylesheets/rapido-css/susy/_susy_isolation.scss",
    "stylesheets/rapido-css/susy/_susy_margin.scss",
    "stylesheets/rapido-css/susy/_susy_media.scss",
    "stylesheets/rapido-css/susy/_susy_padding.scss",
    "stylesheets/rapido-css/susy/_susy_settings.scss",
    "stylesheets/rapido-css/susy/_susy_support.scss",
    "stylesheets/rapido-css/susy/_susy_units.scss",
    "stylesheets/rapido-css/utilities/_animations.scss",
    "stylesheets/rapido-css/utilities/_debug.scss",
    "stylesheets/rapido-css/utilities/_helper-classes.scss",
    "stylesheets/rapido-css/utilities/_icon-fonts.scss",
    "stylesheets/rapido-css/utilities/_media-queries.scss",
    "stylesheets/rapido-css/utilities/_mixins.scss",
    "stylesheets/rapido-css/utilities/_retina-sprites.scss",
    "stylesheets/rapido-css/utilities/_sprites.scss",
    "test/helper.rb",
    "test/test_rapido-css.rb"
  ]
  s.homepage = "http://github.com/raffone/rapido-css"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.25"
  s.summary = "TODO: one-line summary of your gem"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<compass>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.8.4"])
    else
      s.add_dependency(%q<compass>, [">= 0"])
      s.add_dependency(%q<jeweler>, ["~> 1.8.4"])
    end
  else
    s.add_dependency(%q<compass>, [">= 0"])
    s.add_dependency(%q<jeweler>, ["~> 1.8.4"])
  end
end

